#!/bin/env zsh 
#


fman() {
  man -k . \
  | fzf \
    --ansi \
    --prompt='man> ' \
    --preview 'man {1} {2} | grep --color=always -E "^|^NAME|^SYNOPSIS|^DESCRIPTION|^OPTIONS"' \
    --preview-window=right:70%:wrap \
  | awk '{print $1, $2}' | xargs man
}

fman
# cd "$HOME/.config/dwm"
# nvim "config.def.h"
